[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsdom", "@mozilla/readability", "axios"]